### ISSUE TITLE
redux 2.0

### ISSUE THREAD

**Issue by ghost** [khtdr/redux-react-koa-isomorphic-counter-example#3]
redux reached 2.0 ;)) 
https://github.com/rackt/redux/blob/master/package.json

**Comment by khtdr** [comment]
seriously already? ha, thanks for the heads up. I will take a look at what needs changed to stay compatible.

**Comment by ghost** [comment]
yee. updating react/redux boilerplates might become full-time job in near feature ;)) ... 
p.s. thnx for your work. i'm new to ES6/Koa/React staff and this repo was the easiest to understand

**Comment by khtdr** [comment]
Finally got around to this :) Upgraded React and Redux to the latest
